FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN apk add --no-cache --virtual .gyp python3 make g++
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./
RUN apk add --no-cache --virtual .gyp python3 make g++
RUN npm ci --only=production
# Cài đặt thêm dotenv-cli
RUN npm install -g dotenv-cli
COPY .env.production ./

# Đảm bảo expose port 3000
EXPOSE 3000

# Sử dụng node thay vì npm để tránh các vấn đề với signal
CMD ["node", "dist/main"]
