version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mtls_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
